# Dataset DHRD-SE
python main.py --model_name RepRec --dataset DHRD_se --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,2,5,10 --regenerate 0 --loss_n BPR --history_max 20 --lr 5e-3 --l2 0 --sample_for_train 0 --train_exploration 0 --test_exploration 0 --train_repeat 1
python main.py --model_name ExpRec --dataset DHRD_se --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 2e-4 --l2 0 --sample_for_train 1 --num_neg 4 --eval_batch_size 32 --train_exploration 1 --train_ignore_repeat 0 --situation_layers 8 --neighbor_num 5

python main.py --model_name ReCANet --dataset DHRD_se --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 5e-3 --l2 1e-4 --u_emb_size 64 --i_emb_size 64 --m_emb_size 64 --history_w 5 --history_max 30 --layers "[64,64,64]" --dropout 0.2 --train_repeat 1 --eval_batch_size 8
python main.py --model_name FM --dataset DHRD_se --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 1e-3 --l2 0 --n_layers --sample_for_train 1 --num_neg 4 --train_exploration 0 --test_exploration 0 --eval_batch_size 16
python main.py --model_name FinalMLP --dataset DHRD_se --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 2e-4 --l2 1e-6 --mlp1_hidden_units "[64]" --mlp1_dropout 0.2 --mlp1_batch_norm 1 --mlp2_hidden_units "[64]" --mlp2_dropout 0.2 --mlp2_batch_norm 1 --fs_hidden_units "[64]" --fs1_context none --fs2_context situation --sample_for_train 1 --num_neg 4 --train_exploration 0 --test_exploration 0 --eval_batch_size 8
python main.py --model_name DIN --dataset DHRD_se --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 5e-3 --l2 0 --history_max 20 --sample_for_train 1 --train_exploration 0 --test_exploration 0 --num_neg 4 --eval_batch_size 4
python main.py --model_name SDIM --dataset DHRD_se --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --gpu 2 --lr 1e-3 --l2 1e-6 --sample_for_train 1 --num_neg 4 --eval_batch_size 4 --short_sequence_field ["item","situation"] --short_target_field ["item","situation"] --long_sequence_field ["item"] --long_target_field ["item"] --all_group_one 0 --dnn_hidden_units [128,64] --net_dropout 0 --batch_norm 0
python main.py --model_name SNPR --dataset DHRD_se_SNPR --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 5e-3 --l2 0 --sample_for_train 1 --num_neg 4 --eval_batch_size 4 --num_heads 2 --num_layers 1 --lambda_r 0.2


# Dataset DHRD-SG
python main.py --model_name RepRec --dataset DHRD_sg --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --history_max 20 --lr 5e-3 --l2 0 --sample_for_train 0 --train_exploration 0 --test_exploration 0 --train_repeat 1
python main.py --model_name ExpRec --dataset DHRD_sg --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 1e-3 --l2 1e-6 --sample_for_train 1 --num_neg 4 --eval_batch_size 16 --eval_batch_size_dev 64 --train_exploration 1 --train_ignore_repeat 0 --situation_layers 3

python main.py --model_name ReCANet --dataset DHRD_sg --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 5e-3 --l2 1e-6 --u_emb_size 64 --i_emb_size 64 --m_emb_size 64 --history_w 10 --history_max 20 --layers "[64,64,64]" --dropout 0.5 --train_repeat 1 --eval_batch_size 8
python main.py --model_name FM --dataset DHRD_sg --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 2e-4 --l2 0 --n_layers --sample_for_train 1 --num_neg 4 --train_exploration 0 --test_exploration 0 --epoch 100 --early_stop 10
python main.py --model_name FinalMLP --dataset DHRD_sg --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 2e-4 --l2 1e-6 --mlp1_hidden_units "[64,64]" --mlp1_dropout 0.2 --mlp1_batch_norm 1 --mlp2_hidden_units "[64,64]" --mlp2_dropout 0.2 --mlp2_batch_norm 1 --fs_hidden_units "[64,64]" --fs1_context all --fs2_context all --sample_for_train 1 --num_neg 4 --train_exploration 0 --test_exploration 0 --eval_batch_size 8 --eval_batch_size_dev 64
python main.py --model_name DIN --dataset DHRD_sg --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 5e-3 --l2 1e-6 --history_max 10 --sample_for_train 1 --train_exploration 0 --test_exploration 0 --num_neg 4 --eval_batch_size 4 --eval_batch_size_dev 32
python main.py --model_name SDIM --dataset DHRD_sg --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 1e-3 --l2 1e-6 --sample_for_train 1 --num_neg 4 --eval_batch_size 4 --eval_batch_size_dev 64 --short_sequence_field '["item","situation"]' --short_target_field '["item","situation"]' --long_sequence_field '["situation"]' --long_target_field '["situation"]' --dnn_hidden_units '[64]' --net_dropout 0 --early_stop 10
python main.py --model_name SNPR --dataset DHRD_sg_SNPR --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 1e-3 --l2 0 --sample_for_train 1 --num_neg 4 --eval_batch_size 4 --early_stop 10

# Dataset TRD
python main.py --model_name RepRec --dataset TRD --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --history_max 30 --lr 5e-3 --l2 1e-6 --sample_for_train 0 --train_exploration 0 --test_exploration 0 --train_repeat 1
python main.py --model_name ExpRec --dataset TRD --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 2e-4 --l2 1e-4 --sample_for_train 1 --num_neg 4 --eval_batch_size 32 --train_exploration 1 --train_ignore_repeat 0 --situation_layers 3 --neighbor_num 5

python main.py --model_name ReCANet --dataset TRD --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 5e-3 --l2 1e-4 --u_emb_size 64 --i_emb_size 64 --m_emb_size 64 --history_w 3 --history_max 10 --layers "[64]" --dropout 0.2 --train_repeat 1 --eval_batch_size 8
python main.py --model_name FM_exp --dataset TRD --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 2e-4 --l2 0 --n_layers --sample_for_train 1 --num_neg 4 --train_exploration 0 --test_exploration 0
python main.py --model_name FinalMLP --dataset TRD --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 2e-4 --l2 1e-4 --mlp1_hidden_units "[64]" --mlp1_dropout 0.2 --mlp1_batch_norm 1 --mlp2_hidden_units "[64]" --mlp2_dropout 0.2 --mlp2_batch_norm 1 --fs_hidden_units "[64,64]" --fs1_context all --fs2_context all --sample_for_train 1 --num_neg 4 --train_exploration 0 --test_exploration 0 --eval_batch_size 8 --eval_batch_size_dev 64
python main.py --model_name DINrepeat --dataset TRD --path ../data/ --include_item_features 1 --include_context_features 1 --use_context_features 1 --metric HR,NDCG --topk 3,5,10 --regenerate 0 --loss_n BPR --lr 5e-3 --l2 1e-6 --history_max 20 --sample_for_train 1 --train_exploration 0 --test_exploration 0 --num_neg 4 --eval_batch_size 4 --eval_batch_size_dev 32
python main.py --model_name SDIM --dataset TRD --path ../data/ --include_item_features 1 --include_context_features 1 --metric HR,NDCG --topk 3,5,10 --loss_n BPR --lr 1e-3 --l2 1e-6 --sample_for_train 1 --num_neg 4 --eval_batch_size 4 --eval_batch_size_dev 32 --short_sequence_field '["item","situation"]' --short_target_field '["item","situation"]' --long_sequence_field '["item"]' --long_target_field '["item"]'

